#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libproxy
Version  : 0.4.18
Release  : 2
URL      : https://github.com/libproxy/libproxy/releases/download/0.4.18/libproxy-0.4.18.tar.xz
Source0  : https://github.com/libproxy/libproxy/releases/download/0.4.18/libproxy-0.4.18.tar.xz
Summary  : Proxy Configuration Library
Group    : Development/Tools
License  : LGPL-2.1
Requires: libproxy-bin = %{version}-%{release}
Requires: libproxy-data = %{version}-%{release}
Requires: libproxy-lib = %{version}-%{release}
Requires: libproxy-libexec = %{version}-%{release}
Requires: libproxy-license = %{version}-%{release}
Requires: libproxy-python = %{version}-%{release}
Requires: libproxy-python3 = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : perl
BuildRequires : pkg-config
BuildRequires : pkgconfig(dbus-1)
BuildRequires : pkgconfig(duktape)
BuildRequires : pkgconfig(libnm)

%description
Thanks for trying libproxy!
To use libproxy in your application, check out the external API in the
proxy.h.

%package bin
Summary: bin components for the libproxy package.
Group: Binaries
Requires: libproxy-data = %{version}-%{release}
Requires: libproxy-libexec = %{version}-%{release}
Requires: libproxy-license = %{version}-%{release}

%description bin
bin components for the libproxy package.


%package data
Summary: data components for the libproxy package.
Group: Data

%description data
data components for the libproxy package.


%package dev
Summary: dev components for the libproxy package.
Group: Development
Requires: libproxy-lib = %{version}-%{release}
Requires: libproxy-bin = %{version}-%{release}
Requires: libproxy-data = %{version}-%{release}
Provides: libproxy-devel = %{version}-%{release}
Requires: libproxy = %{version}-%{release}

%description dev
dev components for the libproxy package.


%package lib
Summary: lib components for the libproxy package.
Group: Libraries
Requires: libproxy-data = %{version}-%{release}
Requires: libproxy-libexec = %{version}-%{release}
Requires: libproxy-license = %{version}-%{release}

%description lib
lib components for the libproxy package.


%package libexec
Summary: libexec components for the libproxy package.
Group: Default
Requires: libproxy-license = %{version}-%{release}

%description libexec
libexec components for the libproxy package.


%package license
Summary: license components for the libproxy package.
Group: Default

%description license
license components for the libproxy package.


%package python
Summary: python components for the libproxy package.
Group: Default
Requires: libproxy-python3 = %{version}-%{release}

%description python
python components for the libproxy package.


%package python3
Summary: python3 components for the libproxy package.
Group: Default
Requires: python3-core

%description python3
python3 components for the libproxy package.


%prep
%setup -q -n libproxy-0.4.18
cd %{_builddir}/libproxy-0.4.18

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1664374717
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
%cmake .. -DBIPR=ON
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1664374717
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libproxy
cp %{_builddir}/libproxy-%{version}/COPYING %{buildroot}/usr/share/package-licenses/libproxy/01a6b4bf79aca9b556822601186afab86e8c4fbf || :
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/proxy

%files data
%defattr(-,root,root,-)
/usr/share/cmake/*

%files dev
%defattr(-,root,root,-)
/usr/include/proxy.h
/usr/lib64/libproxy.so
/usr/lib64/pkgconfig/libproxy-1.0.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libproxy.so.1
/usr/lib64/libproxy.so.1.0.0
/usr/lib64/libproxy/0.4.18/modules/config_gnome3.so
/usr/lib64/libproxy/0.4.18/modules/config_kde.so
/usr/lib64/libproxy/0.4.18/modules/config_pacrunner.so
/usr/lib64/libproxy/0.4.18/modules/network_networkmanager.so

%files libexec
%defattr(-,root,root,-)
/usr/libexec/pxgsettings

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libproxy/01a6b4bf79aca9b556822601186afab86e8c4fbf

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
